package gov.iti.jets.entity;
// default package
// Generated Apr 19, 2022, 11:05:40 PM by Hibernate Tools 6.0.0.Beta2


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="rest_soap_api"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Admin  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private Set<Clerk> clerks = new HashSet<Clerk>(0);

    public Admin() {
    }

    public Admin(String name, String email, Set<Clerk> clerks) {
       this.name = name;
       this.email = email;
       this.clerks = clerks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", unique=true, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="admin")
    public Set<Clerk> getClerks() {
        return this.clerks;
    }
    
    public void setClerks(Set<Clerk> clerks) {
        this.clerks = clerks;
    }




}


