package gov.iti.jets.persistence.entity;// default package
// Generated Apr 24, 2022, 2:56:59 PM by Hibernate Tools 6.0.0.Beta2


import gov.iti.jets.persistence.entity.Order;
import jakarta.persistence.*;

import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

/**
 * gov.iti.jets.persistence.entity.Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="api"
)
public class Customer  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String phone;
     private Set<Order> orders = new HashSet<Order>(0);

    public Customer() {
    }

    public Customer(String name, String email, String phone, Set<Order> orders) {
       this.name = name;
       this.email = email;
       this.phone = phone;
       this.orders = orders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", length=11)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="customer", cascade = CascadeType.REMOVE)
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


