package gov.iti.jets.persistence.entity;// default package
// Generated Apr 24, 2022, 1:14:31 PM by Hibernate Tools 6.0.0.Beta2


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * gov.iti.jets.persistence.entity.Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="api"
)
public class Product  implements java.io.Serializable {


     private Integer id;
     private String description;
     private String name;
     private Integer price;
     private Set<Category> categories = new HashSet<Category>(0);
     private Set<Order> orders = new HashSet<Order>(0);

    public Product() {
    }

    public Product(String description, String name, Integer price, Set<Category> categories, Set<Order> orders) {
       this.description = description;
       this.name = name;
       this.price = price;
       this.categories = categories;
       this.orders = orders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="description", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="price")
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="product_category", catalog="api", joinColumns = { 
        @JoinColumn(name="product_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="category_id", nullable=false, updatable=false) })
    public Set<Category> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Category> categories) {
        this.categories = categories;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="product_order", catalog="api", joinColumns = { 
        @JoinColumn(name="prod_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="order_id", nullable=false, updatable=false) })
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


