package gov.iti.jets.customer.entity;
// default package
// Generated Apr 19, 2022, 11:05:40 PM by Hibernate Tools 6.0.0.Beta2


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import gov.iti.jets.order.entity.Order;
import gov.iti.jets.shoppingcart.entity.Shoppingcart;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="rest_soap_api"
)
public class Customer  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String phone;
     private Set<Order> orders = new HashSet<Order>(0);
     private Set<Shoppingcart> shoppingcarts = new HashSet<Shoppingcart>(0);

    public Customer() {
    }

    public Customer(String name, String email, String phone, Set<Order> orders, Set<Shoppingcart> shoppingcarts) {
       this.name = name;
       this.email = email;
       this.phone = phone;
       this.orders = orders;
       this.shoppingcarts = shoppingcarts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customer")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customer")
    public Set<Shoppingcart> getShoppingcarts() {
        return this.shoppingcarts;
    }
    
    public void setShoppingcarts(Set<Shoppingcart> shoppingcarts) {
        this.shoppingcarts = shoppingcarts;
    }




}


