package gov.iti.jets.persistence.entity;// default package
// Generated Apr 24, 2022, 1:14:31 PM by Hibernate Tools 6.0.0.Beta2


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * gov.iti.jets.persistence.entity.Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="api"
)
public class Category  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Product> products = new HashSet<>(0);

    public Category() {
    }

    public Category(String name, Set<Product> products) {
       this.name = name;
       this.products = products;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="product_category", catalog="api", joinColumns = { 
        @JoinColumn(name="category_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="product_id", nullable=false, updatable=false) })
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


